 # Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 # SPDX-License-Identifier: MIT-0
 #
 # Permission is hereby granted, free of charge, to any person obtaining a copy of this
 # software and associated documentation files (the "Software"), to deal in the Software
 # without restriction, including without limitation the rights to use, copy, modify,
 # merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so.
 #
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 # INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 # PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 # HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 # SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: 2010-09-09
Description: This Template will create the supporting infrastructure for the AWS Security Blog Post about integrating SSM InSpec with Security Hub
Resources:
  SSMtoSecHubLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: SSMComplianceInSpec_to_SecurityHub
      Description: Pushes enriched information about instances that fail InSpec checks from SSM Compliance to Security Hub
      Handler: index.lambda_handler
      MemorySize: 384
      Role: !GetAtt SSMtoSecHubLambdaRole.Arn
      Runtime: python3.7
      Timeout: 70
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              print("REPLACE ME WITH THE GITHUB CODE")
  SSMtoSecHubLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Policies:
      - PolicyName: SSM2SecHub-LambdaPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            Resource: '*'
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
          - Effect: Allow
            Action:
            - ssm:ListComplianceItems
            - ssm:DescribeInstanceInformation
            - securityhub:BatchImportFindings
            - ec2:DescribeNetworkAcls
            - ec2:DescribeInstances
            Resource: '*'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: { Service: lambda.amazonaws.com }
          Action:
          - sts:AssumeRole
  SSMtoSecHubEventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Name: SSM_2_SecHub_CWE
      Description: "Pushes enriched information about instances that fail InSpec checks from SSM Compliance to Security Hub"
      EventPattern: 
        source: 
          - aws.ssm
        detail-type: 
          - Configuration Compliance State Change
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "SSMtoSecHubLambdaFunction"
              - "Arn"
          Id: "SSM_2_SecHub_CWE"
  SSMtoSecHubCWEPermissions: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "SSMtoSecHubLambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "SSMtoSecHubEventRule"
          - "Arn"
  SSMtoSecHubS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sechub-inspec-profiles-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256